export const testCols = [
  {
    name: 'Mr Dr. 1, mdspatient',
    dob: '15 February 1992',
    clinicId: '12345',
    baxterId: 'O-BXEUS-1172210',
    physician: 'Dr. pal, charan',
    status: 'Active',
  },
  {
    name: 'Mrs. Jane Doe, patient',
    dob: '3 March 1985',
    clinicId: '23456',
    baxterId: 'O-BXEUS-1172211',
    physician: 'Dr. Smith, John',
    status: 'Inactive',
  },
  {
    name: 'Mr. John Roe, patient',
    dob: '20 July 1978',
    clinicId: '34567',
    baxterId: 'O-BXEUS-1172212',
    physician: 'Dr. Brown, Susan',
    status: 'Active',
  },
  {
    name: 'Ms. Emily Clark, mdspatient',
    dob: '11 August 1990',
    clinicId: '45678',
    baxterId: 'O-BXEUS-1172213',
    physician: 'Dr. Green, Lily',
    status: 'Inactive',
  },
  {
    name: 'Dr. Henry Mills, mdspatient',
    dob: '5 January 1982',
    clinicId: '56789',
    baxterId: 'O-BXEUS-1172214',
    physician: 'Dr. Wilson, Tom',
    status: 'Active',
  },
  {
    name: 'Mrs. Linda Hall, patient',
    dob: '18 June 1975',
    clinicId: '67890',
    baxterId: 'O-BXEUS-1172215',
    physician: 'Dr. King, Anna',
    status: 'Inactive',
  },
  {
    name: 'Mr. Charles White, mdspatient',
    dob: '9 September 1988',
    clinicId: '78901',
    baxterId: 'O-BXEUS-1172216',
    physician: 'Dr. Moore, Alex',
    status: 'Active',
  },
  {
    name: 'Ms. Sarah Lewis, patient',
    dob: '22 November 1995',
    clinicId: '89012',
    baxterId: 'O-BXEUS-1172217',
    physician: 'Dr. Hill, Nancy',
    status: 'Inactive',
  },
  {
    name: 'Mr. Michael Davis, patient',
    dob: '14 May 1980',
    clinicId: '90123',
    baxterId: 'O-BXEUS-1172218',
    physician: 'Dr. Adams, George',
    status: 'Active',
  },
  {
    name: 'Mrs. Patricia Martinez, mdspatient',
    dob: '7 December 1983',
    clinicId: '01234',
    baxterId: 'O-BXEUS-1172219',
    physician: 'Dr. Lopez, Carmen',
    status: 'Inactive',
  },
  {
    name: 'Mr. Thomas Garcia, patient',
    dob: '26 April 1977',
    clinicId: '13245',
    baxterId: 'O-BXEUS-1172220',
    physician: 'Dr. Roberts, Paul',
    status: 'Active',
  },
  {
    name: 'Ms. Karen Martinez, mdspatient',
    dob: '8 February 1991',
    clinicId: '24356',
    baxterId: 'O-BXEUS-1172221',
    physician: 'Dr. Evans, Grace',
    status: 'Inactive',
  },
  {
    name: 'Mr. Steven Taylor, patient',
    dob: '16 October 1979',
    clinicId: '35467',
    baxterId: 'O-BXEUS-1172222',
    physician: 'Dr. Turner, Mark',
    status: 'Active',
  },
  {
    name: 'Mrs. Barbara Moore, mdspatient',
    dob: '5 December 1986',
    clinicId: '46578',
    baxterId: 'O-BXEUS-1172223',
    physician: 'Dr. Phillips, Elaine',
    status: 'Inactive',
  },
  {
    name: 'Mr. James Brown, patient',
    dob: '12 March 1989',
    clinicId: '57689',
    baxterId: 'O-BXEUS-1172224',
    physician: 'Dr. Campbell, Larry',
    status: 'Active',
  },
  {
    name: 'Ms. Laura Wilson, patient',
    dob: '29 July 1984',
    clinicId: '68790',
    baxterId: 'O-BXEUS-1172225',
    physician: 'Dr. Parker, Olivia',
    status: 'Inactive',
  },
  {
    name: 'Mrs. Cynthia Hall, mdspatient',
    dob: '13 June 1987',
    clinicId: '79801',
    baxterId: 'O-BXEUS-1172226',
    physician: 'Dr. Stewart, Mia',
    status: 'Active',
  },
  {
    name: 'Mr. David Johnson, patient',
    dob: '23 September 1976',
    clinicId: '80912',
    baxterId: 'O-BXEUS-1172227',
    physician: 'Dr. Ward, Emily',
    status: 'Inactive',
  },
  {
    name: 'Ms. Jennifer White, patient',
    dob: '15 April 1993',
    clinicId: '92023',
    baxterId: 'O-BXEUS-1172228',
    physician: 'Dr. Baker, Rachel',
    status: 'Active',
  },
  {
    name: 'Mr. Anthony Green, mdspatient',
    dob: '19 December 1981',
    clinicId: '03124',
    baxterId: 'O-BXEUS-1172229',
    physician: 'Dr. Mitchell, Jason',
    status: 'Inactive',
  },
  {
    name: 'Mr Dr. 1, mdspatient',
    dob: '15 February 1992',
    clinicId: '12345',
    baxterId: 'O-BXEUS-1172210',
    physician: 'Dr. pal, charan',
    status: 'Active',
  },
  {
    name: 'Mrs. Jane Doe, patient',
    dob: '3 March 1985',
    clinicId: '23456',
    baxterId: 'O-BXEUS-1172211',
    physician: 'Dr. Smith, John',
    status: 'Inactive',
  },
  {
    name: 'Mr. John Roe, patient',
    dob: '20 July 1978',
    clinicId: '34567',
    baxterId: 'O-BXEUS-1172212',
    physician: 'Dr. Brown, Susan',
    status: 'Active',
  },
  {
    name: 'Ms. Emily Clark, mdspatient',
    dob: '11 August 1990',
    clinicId: '45678',
    baxterId: 'O-BXEUS-1172213',
    physician: 'Dr. Green, Lily',
    status: 'Inactive',
  },
  {
    name: 'Dr. Henry Mills, mdspatient',
    dob: '5 January 1982',
    clinicId: '56789',
    baxterId: 'O-BXEUS-1172214',
    physician: 'Dr. Wilson, Tom',
    status: 'Active',
  },
  {
    name: 'Mrs. Linda Hall, patient',
    dob: '18 June 1975',
    clinicId: '67890',
    baxterId: 'O-BXEUS-1172215',
    physician: 'Dr. King, Anna',
    status: 'Inactive',
  },
  {
    name: 'Mr. Charles White, mdspatient',
    dob: '9 September 1988',
    clinicId: '78901',
    baxterId: 'O-BXEUS-1172216',
    physician: 'Dr. Moore, Alex',
    status: 'Active',
  },
  {
    name: 'Ms. Sarah Lewis, patient',
    dob: '22 November 1995',
    clinicId: '89012',
    baxterId: 'O-BXEUS-1172217',
    physician: 'Dr. Hill, Nancy',
    status: 'Inactive',
  },
  {
    name: 'Mr. Michael Davis, patient',
    dob: '14 May 1980',
    clinicId: '90123',
    baxterId: 'O-BXEUS-1172218',
    physician: 'Dr. Adams, George',
    status: 'Active',
  },
  {
    name: 'Mrs. Patricia Martinez, mdspatient',
    dob: '7 December 1983',
    clinicId: '01234',
    baxterId: 'O-BXEUS-1172219',
    physician: 'Dr. Lopez, Carmen',
    status: 'Inactive',
  },
  {
    name: 'Mr. Thomas Garcia, patient',
    dob: '26 April 1977',
    clinicId: '13245',
    baxterId: 'O-BXEUS-1172220',
    physician: 'Dr. Roberts, Paul',
    status: 'Active',
  },
  {
    name: 'Ms. Karen Martinez, mdspatient',
    dob: '8 February 1991',
    clinicId: '24356',
    baxterId: 'O-BXEUS-1172221',
    physician: 'Dr. Evans, Grace',
    status: 'Inactive',
  },
  {
    name: 'Mr. Steven Taylor, patient',
    dob: '16 October 1979',
    clinicId: '35467',
    baxterId: 'O-BXEUS-1172222',
    physician: 'Dr. Turner, Mark',
    status: 'Active',
  },
  {
    name: 'Mrs. Barbara Moore, mdspatient',
    dob: '5 December 1986',
    clinicId: '46578',
    baxterId: 'O-BXEUS-1172223',
    physician: 'Dr. Phillips, Elaine',
    status: 'Inactive',
  },
  {
    name: 'Mr. James Brown, patient',
    dob: '12 March 1989',
    clinicId: '57689',
    baxterId: 'O-BXEUS-1172224',
    physician: 'Dr. Campbell, Larry',
    status: 'Active',
  },
  {
    name: 'Ms. Laura Wilson, patient',
    dob: '29 July 1984',
    clinicId: '68790',
    baxterId: 'O-BXEUS-1172225',
    physician: 'Dr. Parker, Olivia',
    status: 'Inactive',
  },
  {
    name: 'Mrs. Cynthia Hall, mdspatient',
    dob: '13 June 1987',
    clinicId: '79801',
    baxterId: 'O-BXEUS-1172226',
    physician: 'Dr. Stewart, Mia',
    status: 'Active',
  },
  {
    name: 'Mr. David Johnson, patient',
    dob: '23 September 1976',
    clinicId: '80912',
    baxterId: 'O-BXEUS-1172227',
    physician: 'Dr. Ward, Emily',
    status: 'Inactive',
  },
  {
    name: 'Ms. Jennifer White, patient',
    dob: '15 April 1993',
    clinicId: '92023',
    baxterId: 'O-BXEUS-1172228',
    physician: 'Dr. Baker, Rachel',
    status: 'Active',
  },
  {
    name: 'Mr. Anthony Green, mdspatient',
    dob: '19 December 1981',
    clinicId: '03124',
    baxterId: 'O-BXEUS-1172229',
    physician: 'Dr. Mitchell, Jason',
    status: 'Inactive',
  },
  {
    name: 'Mr Dr. 1, mdspatient',
    dob: '15 February 1992',
    clinicId: '12345',
    baxterId: 'O-BXEUS-1172210',
    physician: 'Dr. pal, charan',
    status: 'Active',
  },
  {
    name: 'Mrs. Jane Doe, patient',
    dob: '3 March 1985',
    clinicId: '23456',
    baxterId: 'O-BXEUS-1172211',
    physician: 'Dr. Smith, John',
    status: 'Inactive',
  },
  {
    name: 'Mr. John Roe, patient',
    dob: '20 July 1978',
    clinicId: '34567',
    baxterId: 'O-BXEUS-1172212',
    physician: 'Dr. Brown, Susan',
    status: 'Active',
  },
  {
    name: 'Ms. Emily Clark, mdspatient',
    dob: '11 August 1990',
    clinicId: '45678',
    baxterId: 'O-BXEUS-1172213',
    physician: 'Dr. Green, Lily',
    status: 'Inactive',
  },
  {
    name: 'Dr. Henry Mills, mdspatient',
    dob: '5 January 1982',
    clinicId: '56789',
    baxterId: 'O-BXEUS-1172214',
    physician: 'Dr. Wilson, Tom',
    status: 'Active',
  },
  {
    name: 'Mrs. Linda Hall, patient',
    dob: '18 June 1975',
    clinicId: '67890',
    baxterId: 'O-BXEUS-1172215',
    physician: 'Dr. King, Anna',
    status: 'Inactive',
  },
  {
    name: 'Mr. Charles White, mdspatient',
    dob: '9 September 1988',
    clinicId: '78901',
    baxterId: 'O-BXEUS-1172216',
    physician: 'Dr. Moore, Alex',
    status: 'Active',
  },
  {
    name: 'Ms. Sarah Lewis, patient',
    dob: '22 November 1995',
    clinicId: '89012',
    baxterId: 'O-BXEUS-1172217',
    physician: 'Dr. Hill, Nancy',
    status: 'Inactive',
  },
  {
    name: 'Mr. Michael Davis, patient',
    dob: '14 May 1980',
    clinicId: '90123',
    baxterId: 'O-BXEUS-1172218',
    physician: 'Dr. Adams, George',
    status: 'Active',
  },
  {
    name: 'Mrs. Patricia Martinez, mdspatient',
    dob: '7 December 1983',
    clinicId: '01234',
    baxterId: 'O-BXEUS-1172219',
    physician: 'Dr. Lopez, Carmen',
    status: 'Inactive',
  },
  {
    name: 'Mr. Thomas Garcia, patient',
    dob: '26 April 1977',
    clinicId: '13245',
    baxterId: 'O-BXEUS-1172220',
    physician: 'Dr. Roberts, Paul',
    status: 'Active',
  },
  {
    name: 'Ms. Karen Martinez, mdspatient',
    dob: '8 February 1991',
    clinicId: '24356',
    baxterId: 'O-BXEUS-1172221',
    physician: 'Dr. Evans, Grace',
    status: 'Inactive',
  },
  {
    name: 'Mr. Steven Taylor, patient',
    dob: '16 October 1979',
    clinicId: '35467',
    baxterId: 'O-BXEUS-1172222',
    physician: 'Dr. Turner, Mark',
    status: 'Active',
  },
  {
    name: 'Mrs. Barbara Moore, mdspatient',
    dob: '5 December 1986',
    clinicId: '46578',
    baxterId: 'O-BXEUS-1172223',
    physician: 'Dr. Phillips, Elaine',
    status: 'Inactive',
  },
  {
    name: 'Mr. James Brown, patient',
    dob: '12 March 1989',
    clinicId: '57689',
    baxterId: 'O-BXEUS-1172224',
    physician: 'Dr. Campbell, Larry',
    status: 'Active',
  },
  {
    name: 'Ms. Laura Wilson, patient',
    dob: '29 July 1984',
    clinicId: '68790',
    baxterId: 'O-BXEUS-1172225',
    physician: 'Dr. Parker, Olivia',
    status: 'Inactive',
  },
  {
    name: 'Mrs. Cynthia Hall, mdspatient',
    dob: '13 June 1987',
    clinicId: '79801',
    baxterId: 'O-BXEUS-1172226',
    physician: 'Dr. Stewart, Mia',
    status: 'Active',
  },
  {
    name: 'Mr. David Johnson, patient',
    dob: '23 September 1976',
    clinicId: '80912',
    baxterId: 'O-BXEUS-1172227',
    physician: 'Dr. Ward, Emily',
    status: 'Inactive',
  },
  {
    name: 'Ms. Jennifer White, patient',
    dob: '15 April 1993',
    clinicId: '92023',
    baxterId: 'O-BXEUS-1172228',
    physician: 'Dr. Baker, Rachel',
    status: 'Active',
  },
  {
    name: 'Mr. Anthony Green, mdspatient',
    dob: '19 December 1981',
    clinicId: '03124',
    baxterId: 'O-BXEUS-1172229',
    physician: 'Dr. Mitchell, Jason',
    status: 'Inactive',
  },
];
